-- ShortLink Demo 初始化脚本（Docker Compose 会自动建表，此脚本用于手动演示 / 截图）

CREATE DATABASE IF NOT EXISTS shortlink DEFAULT CHARACTER SET utf8mb4;

USE shortlink;

CREATE TABLE IF NOT EXISTS link (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  short_code VARCHAR(16) NOT NULL UNIQUE COMMENT '短码（Base62 编码的自增 ID）',
  long_url VARCHAR(2048) NOT NULL COMMENT '原始长链接',
  click_count BIGINT NOT NULL DEFAULT 0 COMMENT '已落库点击量',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1=启用 0=禁用',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短链接表';
